# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage:
  jobs:
  - job: Build
    steps:
     - bash: echo This is building Script!

- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: QaDeploy
  jobs:
  - deployment: QaDeployJob
    environment: Qa
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Qa

